### ISSUE TITLE
Cannot compile / run scrips

### ISSUE THREAD

**Issue by pudility** [xkbeyer/liquid#3]
Hi there! I am super interested in this project but, I am having a little bit of trouble compiling and running scripts. 

### Script
```
printvalue(1);
```
### Command to run
```
$ ./liq test.liq
```

### output
```

Usage:
liq filename -h -d -v -q -i path1;path2
	-h this help text.
	-d debug code generation. Disables the code optimizer pass.
	-v be more verbose.
	-q be quiet.
	-i semicolon separated list of import paths where additional liquid files are located.
```

### Other info
I modified tokens.cpp and removed `register` so I could compile liq.

**Comment by xkbeyer** [comment]
Hi, there is a bug w/ the cmd line parsing.
If you run
`
./liq test.liq -v
`
then it should work.

**Comment by pudility** [comment]
That worked perfectly, thanks.

**Comment by pudility** [comment]
@xkbeyer One more question (but I don't think it is worth opening another issue). Can arrays be passed at function parameters and returned? If so how?

Thanks!

**Comment by xkbeyer** [comment]
Array is a big construction site right now:) No it doesn't work, sorry.

**Comment by pudility** [comment]
No problem - just thought I would check. I am actually working on implementing arrays in a toy language I am working on and was curios how you were doing it. My language is no where near as developed as this one though :).
