### ISSUE TITLE
Builtins missing

### ISSUE THREAD

**Issue by thesecretmaster** [xkbeyer/liquid#4]
I just cloned and built this project, and any examples I try to run throw an error like "LLVM ERROR: Program used external function 'displayln' which could not be resolved!". It appears to happen for any builtin function. I can't see any reason why though.

**Comment by xkbeyer** [comment]
Could you tell me the version of LLVM, compiler and platform you are using?
Do you use the release or the debug build?

**Comment by thesecretmaster** [comment]
LLVM version 6.0.0. I'm running arch linux.
I simply followed the instructions in the readme, then entered the `build` directory and tried runing `./liq ../test_samples/test.liq`

**Comment by xkbeyer** [comment]
Oh, I see, I have the same result. Have to debug...

**Comment by xkbeyer** [comment]
It was a linux only problem. Will push the fix soon.

**Comment by thesecretmaster** [comment]
Thank you!

**Comment by thesecretmaster** [comment]
Pulled, all is working now
