### ISSUE TITLE
Error in running CMake: "The system cannot find the file specified"

### ISSUE THREAD

**Issue by ghost** [xkbeyer/liquid#8]
Hello @xkbeyer, I am new and want to use your repository for my study. As title, is this a bug with **`CMake`** or my **`System`** and how to solve this problem? .. Hope to get your answer! ***(all required settings already done)***
 
![Bug1](https://user-images.githubusercontent.com/105527161/170727958-5b31706a-fa22-42f9-868b-fa8c5c36c0c6.png)

**Comment by xkbeyer** [comment]
If you are using visual studio, could you try to run the command in a "x64 Native Tools Command prompt"?
An other way would be to add the Option -G with the build system you are using.
